// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaaMNbB6c6huPZKNm-ViXeTz19Zbc00Fg',
    appId: '1:106506673930:web:77e5de47fd163421a064f3',
    messagingSenderId: '106506673930',
    projectId: 'ecommerce-e4335',
    authDomain: 'ecommerce-e4335.firebaseapp.com',
    storageBucket: 'ecommerce-e4335.firebasestorage.app',
    measurementId: 'G-78JD03Z8FK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdWjx781NE_NhWMu-g1DGBle4dmoiTJoA',
    appId: '1:106506673930:android:7cb614b572577d71a064f3',
    messagingSenderId: '106506673930',
    projectId: 'ecommerce-e4335',
    storageBucket: 'ecommerce-e4335.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7WXfQvPj7qZ8oqf1nzJ6kavnzA-TVFuI',
    appId: '1:106506673930:ios:3171b862f3f59e6ba064f3',
    messagingSenderId: '106506673930',
    projectId: 'ecommerce-e4335',
    storageBucket: 'ecommerce-e4335.firebasestorage.app',
    iosBundleId: 'com.example.groceryStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7WXfQvPj7qZ8oqf1nzJ6kavnzA-TVFuI',
    appId: '1:106506673930:ios:3171b862f3f59e6ba064f3',
    messagingSenderId: '106506673930',
    projectId: 'ecommerce-e4335',
    storageBucket: 'ecommerce-e4335.firebasestorage.app',
    iosBundleId: 'com.example.groceryStore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBaaMNbB6c6huPZKNm-ViXeTz19Zbc00Fg',
    appId: '1:106506673930:web:53aff6c38c86d351a064f3',
    messagingSenderId: '106506673930',
    projectId: 'ecommerce-e4335',
    authDomain: 'ecommerce-e4335.firebaseapp.com',
    storageBucket: 'ecommerce-e4335.firebasestorage.app',
    measurementId: 'G-FJG6NBRX12',
  );
}
